---
title: "Nuclear Explosions"
author: "Alex Huber"
date: "2023-09-07"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(warning=F, message=F, echo = T)
```

```{r reading data, warnings=F}
library(readr)

# Reading in the data from Tidy Tuesday GitHub Repo
nuclear_explosions <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-20/nuclear_explosions.csv")

write.csv(nuclear_explosions, "nuclearExplosionRawData.csv")

```

```{r plot explosions by year with vountry fill}
library(tidyverse)
library(ggthemes)
library(plotly)

# Create ggplot object that displays nuclear explosions per year by country
p1 <- nuclear_explosions %>%
  group_by(year, country) %>%
  summarize(n = n()) %>%
  ggplot() +
  geom_col(aes(x = year, y = n, fill = country)) +
  scale_x_continuous(n.breaks = 12) +
  labs(title = "Nuclear Explosions Per Year By Country (1945-1998)", x = "Year", y = "Number of Explosions") +
  theme_clean()
  
ggplotly(p1)
```
