---
title: "Nuclear Explosions"
author: "Alex Huber"
date: "2023-09-07"
output:
  html_document:
    toc: true
knit: 
  (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = 'index.html'
    )
  })
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(warning=F, message=F, echo = T, out.width="100%")
```

### Reading in Data
```{r}
library(readr)

# Reading in the data originally from Tidy Tuesday GitHub Repo
# https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-20/nuclear_explosions.csv
nuclear_explosions <- read_csv("nuclearExplosionRawData.csv")

```

### Explosions Per Year By Country
```{r}
library(tidyverse)
library(plotly)

# Create dataframe that summarizes the nuber of explosions by country and year
year_country_data <- nuclear_explosions %>%
  group_by(year, country) %>%
  summarize(n = n())

# Create plotly object that displays nuclear explosions per year by country
p1 <- plot_ly(data = year_country_data,
              x = ~year,
              y = ~n,
              type = "bar",
              color = ~country,
              text = ~paste0(year, "<br>", country, ": ", n),
              hoverinfo = "text") %>%
  layout(title = "Global Nuclear Explosions (1945-1998)",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Number of Explosions"),
         barmode = "stack",
         plot_bgcolor = "#e5ecf6")

p1

```

### Type of Explosion Breakdown
```{r}

# Renaming and generalizing categories of explosion types
nuclear_explosions$type <- gsub("AIRDROP|ATMOSPH$|BALLOON|ROCKET", "ATMOSPHERIC", nuclear_explosions$type)
nuclear_explosions$type <- gsub("CRATER|^SURFACE|TOWER", "EARTH SURFACE", nuclear_explosions$type)
nuclear_explosions$type <- gsub("BARGE|SHIP|WATER SU$|WATERSUR", "WATER SURFACE", nuclear_explosions$type)
nuclear_explosions$type <- gsub("UG|TUNNEL|SHAFT.*|MINE|GALLERY", "UNDERGROUND", nuclear_explosions$type)
nuclear_explosions$type <- gsub("UW", "UNDERWATER", nuclear_explosions$type)


# Create dataframe that summarizes the number of explosions by country and year
type_data <- nuclear_explosions %>%
  group_by(type) %>%
  summarize(n = n())

# Create plotly object that displays type distributions of global nuclear explosions 
p2 <- plot_ly(data = type_data,
              type = "pie",
              labels = ~type,
              values = ~n,
              textinfo = "percent",
              text = ~paste0(type, "<br>", n, " events<br>"),
              hoverinfo = "text") %>%
  layout(title = "Type Distribution of Global Nuclear Explosions (1945-1998)")

p2

```


### Explosions Global Distribution
```{r}

# Create plotly object that shows locations of all explosions
p3 <- plot_geo(nuclear_explosions, sizes = c(10,500)) %>%
  add_markers(x = ~longitude,
              y = ~latitude,
              color = ~country,
              size = ~yield_lower,
              text = ~paste0(year, "<br>", country, "<br>", yield_lower, " kilotons TNT"),
              hoverinfo = "text") %>%
  layout(title = list(text = "Global Nuclear Explosions (1945-1998)", font = list(size = 20), y = 0.96),
         legend = list(y = 0.85),
         geo = list(showcountries = TRUE, showland = TRUE, showocean = TRUE, landcolor = "bbdaa4", oceancolor = "a7cdf2"),
         margin = list(t = 0, b = 0, l = 10, r = 10))

p3

```